"""Machine-Readable Reason-Code Registry."""

from enum import Enum, unique


@unique
class ReasonCode(str, Enum):
    # Data Reasons
    DATA_STALE = "DATA_STALE"
    DATA_CORRUPTED = "DATA_CORRUPTED"
    DATA_UNAVAILABLE = "DATA_UNAVAILABLE"

    # Lineage / Parent Reasons
    PARENT_INVALID = "PARENT_INVALID"
    PARENT_VERSION_STALE = "PARENT_VERSION_STALE"
    LINEAGE_INVALID = "LINEAGE_INVALID"
    ORPHANED_OBJECT = "ORPHANED_OBJECT"

    # Execution & Tradeability Reasons
    SPREAD_TOO_HIGH = "SPREAD_TOO_HIGH"
    COST_TOO_HIGH = "COST_TOO_HIGH"
    LIQUIDITY_FAILED = "LIQUIDITY_FAILED"
    EXECUTION_QUALITY_FAILED = "EXECUTION_QUALITY_FAILED"
    OPPORTUNITY_SPACE_INSUFFICIENT = "OPPORTUNITY_SPACE_INSUFFICIENT"

    # News Reasons
    NEWS_LOCKDOWN = "NEWS_LOCKDOWN"
    NEWS_SHOCK = "NEWS_SHOCK"
    NEWS_NORMALIZATION_FAILED = "NEWS_NORMALIZATION_FAILED"

    # Risk Reasons
    RISK_RESTRICTED = "RISK_RESTRICTED"
    RISK_HALTED = "RISK_HALTED"
    ACCOUNT_INFEASIBLE = "ACCOUNT_INFEASIBLE"
    BROKER_CONSTRAINT_FAILED = "BROKER_CONSTRAINT_FAILED"

    # Portfolio Reasons
    PORTFOLIO_CONCENTRATION = "PORTFOLIO_CONCENTRATION"
    CORRELATION_LIMIT = "CORRELATION_LIMIT"
    CURRENCY_EXPOSURE_LIMIT = "CURRENCY_EXPOSURE_LIMIT"

    # PDE / Structure Reasons
    STRUCTURE_INVALIDATED = "STRUCTURE_INVALIDATED"
    PULLBACK_INVALIDATED = "PULLBACK_INVALIDATED"
    RESUMPTION_FAILED = "RESUMPTION_FAILED"

    # TTL Reasons
    TTL_EXPIRED = "TTL_EXPIRED"
    PROGRESS_SHORTFALL = "PROGRESS_SHORTFALL"
    MOMENTUM_DECAY = "MOMENTUM_DECAY"

    # Execution State / Reconciliation Reasons
    EXECUTION_UNKNOWN = "EXECUTION_UNKNOWN"
    EXECUTION_REJECTED = "EXECUTION_REJECTED"
    RECONCILIATION_REQUIRED = "RECONCILIATION_REQUIRED"
    QUARANTINED = "QUARANTINED"
