#ifndef __FFBP_JSON_MQH__
#define __FFBP_JSON_MQH__

// Deliberately small, fail-closed JSON helpers for the fixed FFBP/1 envelope.
// The bridge envelope is canonical JSON generated by Python. The EA accepts
// only the expected scalar field types and treats malformed/ambiguous input as fatal.

string FFBP_JsonEscape(const string s)
{
   string o="";
   int n=StringLen(s);
   for(int i=0;i<n;i++)
   {
      ushort c=StringGetCharacter(s,i);
      if(c=='\\') o+="\\\\";
      else if(c=='\"') o+="\\\"";
      else if(c=='\n') o+="\\n";
      else if(c=='\r') o+="\\r";
      else if(c=='\t') o+="\\t";
      else if(c<32) return ""; // control chars are rejected
      else o+=ShortToString(c);
   }
   return o;
}

bool FFBP_IsHex64(const string s)
{
   if(StringLen(s)!=64) return false;
   for(int i=0;i<64;i++)
   {
      ushort c=StringGetCharacter(s,i);
      bool ok=(c>='0'&&c<='9')||(c>='a'&&c<='f')||(c>='A'&&c<='F');
      if(!ok) return false;
   }
   return true;
}

int FFBP_SkipWs(const string s,int p)
{
   int n=StringLen(s);
   while(p<n)
   {
      ushort c=StringGetCharacter(s,p);
      if(c==' '||c=='\t'||c=='\r'||c=='\n') p++;
      else break;
   }
   return p;
}

bool FFBP_FindKey(const string json,const string key,int &value_start)
{
   string needle="\""+key+"\":";
   int p=StringFind(json,needle);
   if(p<0) return false;
   value_start=FFBP_SkipWs(json,p+StringLen(needle));
   return value_start<StringLen(json);
}

bool FFBP_ParseStringValue(const string json,const string key,string &value)
{
   int p;
   if(!FFBP_FindKey(json,key,p)) return false;
   if(StringGetCharacter(json,p)!='\"') return false;
   p++;
   string out="";
   bool esc=false;
   for(int i=p;i<StringLen(json);i++)
   {
      ushort c=StringGetCharacter(json,i);
      if(esc)
      {
         if(c=='\"'||c=='\\'||c=='/') out+=ShortToString(c);
         else if(c=='n') out+="\n";
         else if(c=='r') out+="\r";
         else if(c=='t') out+="\t";
         else return false;
         esc=false;
      }
      else if(c=='\\') esc=true;
      else if(c=='\"') { value=out; return true; }
      else if(c<32) return false;
      else out+=ShortToString(c);
   }
   return false;
}

bool FFBP_ParseUInt64(const string json,const string key,ulong &value)
{
   int p;
   if(!FFBP_FindKey(json,key,p)) return false;
   int start=p;
   int n=StringLen(json);
   while(p<n)
   {
      ushort c=StringGetCharacter(json,p);
      if(c<'0'||c>'9') break;
      p++;
   }
   if(p==start) return false;
   string t=StringSubstr(json,start,p-start);
   long v=StringToInteger(t);
   if(v<0) return false;
   value=(ulong)v;
   return true;
}

bool FFBP_ParseInt64OrNull(const string json,const string key,long &value,bool &is_null)
{
   int p;
   if(!FFBP_FindKey(json,key,p)) return false;
   if(StringSubstr(json,p,4)=="null") { is_null=true; value=0; return true; }
   is_null=false;
   bool neg=(StringGetCharacter(json,p)=='-');
   if(neg) p++;
   int start=p;
   while(p<StringLen(json))
   {
      ushort c=StringGetCharacter(json,p);
      if(c<'0'||c>'9') break;
      p++;
   }
   if(p==start) return false;
   long v=StringToInteger(StringSubstr(json,start,p-start));
   value=neg?-v:v;
   return true;
}


bool FFBP_ExtractPayloadObject(const string json,string &payload)
{
   int p;
   if(!FFBP_FindKey(json,"payload",p)) return false;
   if(StringGetCharacter(json,p)!='{') return false;
   int start=p,depth=0; bool in_string=false,esc=false;
   for(int i=p;i<StringLen(json);i++)
   {
      ushort c=StringGetCharacter(json,i);
      if(in_string)
      {
         if(esc) { esc=false; continue; }
         if(c=='\\') { esc=true; continue; }
         if(c=='\"') in_string=false;
         continue;
      }
      if(c=='\"') { in_string=true; continue; }
      if(c=='{') depth++;
      else if(c=='}')
      {
         depth--;
         if(depth==0) { payload=StringSubstr(json,start,i-start+1); return true; }
      }
   }
   return false;
}

bool FFBP_ParseUInt(const string json,const string key,uint &value)
{
   ulong v;
   if(!FFBP_ParseUInt64(json,key,v) || v>0xFFFFFFFF) return false;
   value=(uint)v;
   return true;
}

// Remove the exact canonical mac property. Canonical FFBP/1 places keys in
// lexicographic order, so this also validates that mac appears once.
bool FFBP_RemoveMac(const string body,string &authenticated,string &mac)
{
   if(!FFBP_ParseStringValue(body,"mac",mac) || !FFBP_IsHex64(mac)) return false;
   string needle="\"mac\":\""+mac+"\"";
   int p=StringFind(body,needle);
   if(p<0) return false;
   int before=p;
   int after=p+StringLen(needle);
   if(before>0 && StringGetCharacter(body,before-1)==',') before--;
   else if(after<StringLen(body) && StringGetCharacter(body,after)==',') after++;
   else return false;
   authenticated=StringSubstr(body,0,before)+StringSubstr(body,after);
   return true;
}

bool FFBP_BuildEnvelopeNoMac(const string type,const string account_id,const string session_id,
                             const string channel,const ulong seq,const ulong ack,const string cmd_id,
                             const string correlation_id,const long sent_at_ms,const bool deadline_null,
                             const long deadline_ms,const uint flags,const string payload_json,
                             string &body_no_mac)
{
   // Lexicographic key order exactly matches Python json.dumps(sort_keys=True).
   string a=FFBP_JsonEscape(account_id), s=FFBP_JsonEscape(session_id);
   string ch=FFBP_JsonEscape(channel), t=FFBP_JsonEscape(type);
   string ci=FFBP_JsonEscape(correlation_id), cm=FFBP_JsonEscape(cmd_id);
   if(a==""||s==""||ch==""||t==""||payload_json=="") return false;
   string cmd=(cmd_id==""?"null":"\""+cm+"\"");
   string corr=(correlation_id==""?"null":"\""+ci+"\"");
   string deadline=(deadline_null?"null":IntegerToString(deadline_ms));
   body_no_mac="{\"account_id\":\""+a+"\",\"ack\":"+IntegerToString((long)ack)+
               ",\"channel\":\""+ch+"\",\"cmd_id\":"+cmd+
               ",\"correlation_id\":"+corr+",\"deadline_ms\":"+deadline+
               ",\"flags\":"+IntegerToString((long)flags)+",\"payload\":"+payload_json+
               ",\"sent_at_ms\":"+IntegerToString(sent_at_ms)+",\"seq\":"+IntegerToString((long)seq)+
               ",\"session_id\":\""+s+"\",\"type\":\""+t+"\",\"v\":\"FFBP/1\"}";
   return true;
}

#endif
